### ISSUE TITLE
Only ASTs for graph embedding?

### ISSUE THREAD

**Issue by kbarbora** [epicosy/devign#4]
Im trying to recreate devign and I came across your repo. Thank you so much.
I see that on the project (under development) you mention that you only using the ASTs instead as the paper implements the joint graph (in paper 3.1, Graph Generation section).
Do you achieve the graph generation according to the paper or you ignore all the relations introduce by the paper and use only ASTs?

**Comment by epicosy** [comment]
Thank you for your interest Kevin. I didn't finish implementing all the relations, I had to move on with other parts of my thesis. You can try to do it by processing the rest of Joern's CPG into some objects that represent the graphs, and then extend the GraphEmbeddings with it. Follow Pytorch Geometric's documentation on Data Handling of Graphs, to figure out how to represent the adjacency matrix for all the graphs. Was it helpful?

**Comment by kbarbora** [comment]
yes, thank you for your feedback.

**Comment by QiuJYWX** [comment]
@kbarbora  ，
I am now trying to run your devign project. I am confused about the 'step4) Joern' Setup part about installing Joern's command line tools under 'project'\joern\joern-cli\. Would you please provide some detailed information about how to perform the Joern installation? e.g., the file structure of the joern-cli folder when finish installation?

**Comment by QiuJYWX** [comment]
Hi @kbarbora @epicosy 

When I ran python main.py -c, I came across the issue:
Traceback (most recent call last):
File "main.py", line 157, in
main()
File "main.py", line 146, in main
create_task()
File "main.py", line 61, in create_task
graphs = prepare.json_process(PATHS.cpg, json_file)
File "/home/qjy/Desktop/devign/src/prepare/cpg_generator.py", line 79, in json_process
container = [graph_indexing(graph) for graph in cpg_json["functions"] if graph["file"] != "N/A"]
File "/home/qjy/Desktop/devign/src/prepare/cpg_generator.py", line 79, in
container = [graph_indexing(graph) for graph in cpg_json["functions"] if graph["file"] != "N/A"]
KeyError: 'file'

Anyone one can provide me some advice?

**Comment by 1112z-c** [comment]
@QiuJYWX  I have met the same problem, has it been solved？Thanks

**Comment by vo-lar** [comment]
Hi @QiuJYWX @1112z-c，I have met the same problem,do u know how to solve？Thank u.

**Comment by huangyuyan3** [comment]
> Im trying to recreate devign and I came across your repo. Thank you so much. I see that on the project (under development) you mention that you only using the ASTs instead as the paper implements the joint graph (in paper 3.1, Graph Generation section). Do you achieve the graph generation according to the paper or you ignore all the relations introduce by the paper and use only ASTs?

Hello, may I ask if you have completed the implementation of the complete CPG including CFG, PDG, etc.? Could you please help me?
